apiVersion: v1
kind: Secret
metadata:
    name: my-secret
    namespace: default
type: Opaque
data:
    #ENC[AES256_GCM,data:AKmXp1G8syYvZYgLHJofyoYC0Q==,iv:zD1sVUSaRBGFchIiGHJ7GC1yjkKs/XJNFxy2VarIZb4=,tag:khflgYlp0xJ429hGWoWeGA==,type:comment]
    username: ENC[AES256_GCM,data:JR3s8CBTzXQ=,iv:tvjWXFNMx41oETTDdBX3iLE3nWETMSYETn54XHmpR+Q=,tag:Bzv6o5AZlmprIGb/MfVIrg==,type:str]
    #ENC[AES256_GCM,data:BQ8KYvGMDFQuuvh+N4OP8UfdIzbJb7MP,iv:rSvt3oDfbIQIzoOpmf5YWJzKsWkTxvEWLLzoTv9Au2Q=,tag:f8c+8B5xJJdFYpCfATDPyQ==,type:comment]
    password: ENC[AES256_GCM,data:NT1hT5RateU6wDVoq4zl4w==,iv:98I+ufcCO5SLmoaWyAYY76oeiJxPB1M7LWAcb9LM/2A=,tag:+uwoG9qjShBqgfBtmdni2Q==,type:str]
sops:
    lastmodified: "2025-06-16T12:41:12Z"
    mac: ENC[AES256_GCM,data:KPSxxvTixLDUxI7CVqEXb0crHZlOqOzuIOVynXuEpyuitDl33rc3INeGhlnji0E0xYZf0jf/jpzdhOTi0tWs8Jf6Ej99UmsGD/+/OewQXgyW3wSuk5IvLNmmDX6r8u+mLWodzeLsu1DVi/yxo2ESH6Ln894VpuzyJ+WaS7j0yWo=,iv:99I/GRXMaWIm+HjSB4gWUGoqms+yF0eT1NXrKJB46f4=,tag:4tdfXVpKkE0r72dhgjSyYA==,type:str]
    pgp:
        - created_at: "2025-06-16T12:41:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/oGn1kMvF67AQ/9G4pEoELmp+SAlEg8Sl83x5w904nHDOabbJEXd9+Gz1PS
            rR2Ale3GoMy+5gOlVYTM2paJRwBz+6kD0Y9qIclRnibBSW4WJMuQigC7ZZzeGqsI
            s8xCHaTHJtB1feSpUqxP4Lt41iP22+drNdNX9lwOnmD1vk/WO07CVNZynsyzAgrs
            J6+dkcyr8M7T9V6rLEhYoIYksjorKH2z6zrUf/jXiFNq3Ke6tne+MCQku1bSzWtU
            AzLsmpU/CKx4pg3sRSxS7IUf0TBUoUEPpC5nFAPCvcM4WfpIJLC9gdHMWJ5LjHZK
            M/1EASuiPzcQc6ZMG/YCJL2q4dj1JLMaihKQ9yt0aEJ9SWt8hd+vHbaVPwvVhI1p
            gtXZBg9fCL/qTwJIQ0khM4WTlbTMvZLW93jSiGjtUWE7ultD4qkxMKH7rfDKZNzE
            B8bjZFLLjf2fl8RiMNAAH7GGQDorh68TPesdLNVjfYCm5V5f3iBPVJdGSI1Kt/Wh
            gxmEmbyWdSna/0fB47VjK9JrntiIX0q5w550ElFTzBXds6QeHnibydyEFvOz9JO/
            fS6P8O9ovFhupK5Ms9YLbpPjEnaWkGLIkczdbV9CnuRDMc5g9TyR7kfXyhIXfoON
            aDr6uWAoZK3QSvAwpbSx6PYl+h57K+sSzR/MvIsGA1lCA6VZgLXEy85795N2ZlzU
            aAEJAhB0MUsA9kE7dIAENIjYDCkZibaRlNuWXv/znOMyKEKDpUW2/EmoaMR6yzQQ
            fwI+f6bvcvOUCz6zbO1sXF/PllKpnVpJrNFvDfTmKSKukGj/nivt+zZw0j5/PB9K
            3yeshrXRJmNH
            =vGvH
            -----END PGP MESSAGE-----
          fp: 0CF7DD9180E8726727866341C72808AEBD2C13A6
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
